version: '3.8'

services:
  # База данных PostgreSQL
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: emlak
      POSTGRES_USER: emlak
      POSTGRES_PASSWORD: "111"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U emlak"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Парсер для отладки (не запускается автоматически)
  parser:
    build:
      context: .
      dockerfile: docker/parser.Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-emlak}
      - POSTGRES_USER=${POSTGRES_USER:-emlak}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-111}
      - NODE_ENV=development
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - parser_data:/app/data
    # Команда для отладки - просто держим контейнер живым
    command: ["tail", "-f", "/dev/null"]
    restart: "no"

  # Telegram бот с dev токеном
  bot:
    build:
      context: .
      dockerfile: docker/bot.Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-emlak}
      - POSTGRES_USER=${POSTGRES_USER:-emlak}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-111}
      - NODE_ENV=development
      - BOT_TOKEN=${BOT_TOKEN}
    restart: unless-stopped

volumes:
  postgres_data: 
  parser_data: 